export const FETCH_HOME_PAGE_DATA = 'FETCH_HOME_PAGE_DATA';
export const FETCH_HOME_PAGE_DATA_FULFILLED = 'FETCH_HOME_PAGE_DATA_FULFILLED';
export const FETCH_HOME_PAGE_DATA_FAILED = 'FETCH_HOME_PAGE_DATA_FAILED';

export default FETCH_HOME_PAGE_DATA;
