export const FETCH_HOME_PAGE_DATA = 'FETCH_HOME_PAGE_DATA';
export const FETCH_HOME_PAGE_DATA_SUCCESS = 'FETCH_HOME_PAGE_DATA_SUCCESS';
export const FETCH_HOME_PAGE_DATA_FAILURE = 'FETCH_HOME_PAGE_DATA_FAILURE';

export default FETCH_HOME_PAGE_DATA;
